const images = {
   App_logo: require('./splacescreen.png'),
   Image_1: require('./splacescreen.png'),
   Image_2:require('./splacescreen.png'),
   Image_3: require('./splacescreen.png'),
   Image_4: require('./splacescreen.png'),
   Image_5: require('./splacescreen.png'),
   Image_6:require('./splacescreen.png'),
   Image_7: require('./splacescreen.png'),
   Sign: require('./splacescreen.png'),
   Sign1: require('./romsons_logo.jpg'),
   Sign3: require('./logo4.png'),
   profile: require('./images4.jpg'),
   SignUp: require('./splacescreen.png'),
   apple: require('./splacescreen.png'),
   googleicon: require('./splacescreen.png'),
   verify: require('./splacescreen.png'),
   password: require('./splacescreen.png'),
   Check: require('./splacescreen.png'),
   user_1: require('./splacescreen.png'),
   user_2: require('./splacescreen.png'),
   user_3: require('./splacescreen.png'),
   user_4: require('./splacescreen.png'),
   user_5: require('./splacescreen.png'),
   user_6: require('./splacescreen.png'),
   Langauge_1: require('./splacescreen.png'),
}
export default images;